apiVersion: v1
kind: Service
metadata:
  name: movie-recommender
  namespace: ml-project
spec:
  selector:
    app: movie-recommender
  type: NodePort
  ports:
    - port: 8000
      targetPort: 8000
      nodePort: 30800
